# Generated by Django 5.1.6 on 2025-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('cakes', 'Cakes'), ('cookies', 'Cookies'), ('breads', 'Breads'), ('pastries', 'Pastries'), ('others', 'Others')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('allergens', models.CharField(blank=True, help_text='E.g., Nuts, Dairy-Free, Gluten-Free', max_length=255, null=True)),
                ('stock', models.PositiveIntegerField()),
                ('serving_size', models.CharField(blank=True, help_text='E.g., Serves 4-6 people', max_length=100, null=True)),
                ('weight', models.CharField(blank=True, help_text='E.g., 500g', max_length=50, null=True)),
                ('customization_options', models.TextField(blank=True, help_text='E.g., Extra toppings, Special messages', null=True)),
                ('calories_per_serving', models.CharField(blank=True, max_length=50, null=True)),
                ('preparation_time', models.CharField(blank=True, help_text='E.g., 24 hours notice required', max_length=100, null=True)),
                ('delivery_available', models.BooleanField(default=True)),
                ('shelf_life', models.CharField(blank=True, help_text='E.g., Best consumed within 2 days', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('tags', models.CharField(blank=True, help_text='E.g., Vegan, Eggless, Keto-friendly', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
