# Generated by Django 5.2 on 2025-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeddelight',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakeddelight',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
