# Generated by Django 5.1.6 on 2025-03-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_category_image_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
