# Generated by Django 5.2 on 2025-05-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
