# Generated by Django 5.1.6 on 2025-03-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_category_image_category_image_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_base64',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
