# Generated by Django 5.2 on 2025-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_cartitem_discount_price_cartitem_price_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
