# Generated by Django 5.2 on 2025-06-29 03:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
