# Generated by Django 5.2 on 2025-06-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_custaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='custaddress',
            name='custId',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
