# Generated by Django 5.1.6 on 2025-03-27 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_category_image_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('allergen_info', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20)),
                ('serving_size', models.CharField(blank=True, max_length=50, null=True)),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('cake_size', models.CharField(blank=True, max_length=20, null=True)),
                ('flavor_variants', models.CharField(blank=True, max_length=255, null=True)),
                ('add_ons', models.CharField(blank=True, max_length=255, null=True)),
                ('product_images_base64', models.TextField(blank=True, null=True)),
                ('calories', models.CharField(blank=True, max_length=50, null=True)),
                ('nutrition_facts', models.TextField(blank=True, null=True)),
                ('prep_time', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_option', models.CharField(blank=True, choices=[('pickup', 'In-store Pickup'), ('home_delivery', 'Home Delivery')], max_length=20, null=True)),
                ('shelf_life', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
                ('related_products', models.CharField(blank=True, max_length=255, null=True)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.category')),
            ],
        ),
    ]
