# Generated by Django 5.1.7 on 2025-04-18 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_whychooseus_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseus',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
