# Generated by Django 5.1.7 on 2025-04-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_alter_whychooseus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPickBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('link', models.URLField(max_length=500)),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
