# Generated by Django 5.1.7 on 2025-04-19 00:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_adds'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakedDelight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
