# Generated by Django 5.1.7 on 2025-04-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_bakeddelight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeddelight',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
