# Generated by Django 5.1.7 on 2025-04-27 04:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0021_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product_id",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="apis.product",
		null=True,
		blank=True
            ),
            preserve_default=False,
        ),
    ]
