# Generated by Django 5.1.7 on 2025-04-27 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0022_remove_orderitem_product_id_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apis.product"
            ),
        ),
    ]
